// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLog(arg1:string):Promise<void>;

export function GenerateTestLogs():Promise<void>;

export function GetActiveUsers():Promise<number>;

export function GetGroupCount():Promise<number>;

export function GetLogs():Promise<string>;

export function GetOtherServers():Promise<Array<string>>;

export function GetServerIP():Promise<string>;

export function Greet(arg1:string):Promise<string>;
