// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLog(arg1) {
  return window['go']['main']['App']['AddLog'](arg1);
}

export function GenerateTestLogs() {
  return window['go']['main']['App']['GenerateTestLogs']();
}

export function GetActiveUsers() {
  return window['go']['main']['App']['GetActiveUsers']();
}

export function GetGroupCount() {
  return window['go']['main']['App']['GetGroupCount']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetOtherServers() {
  return window['go']['main']['App']['GetOtherServers']();
}

export function GetServerIP() {
  return window['go']['main']['App']['GetServerIP']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
